change tab width to 2 spaces

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -86,62 +86,62 @@ export PATH=$MAVEN_HOME/bin:$PATH
 export PATH=$JAVA_HOME/bin:$PATH
 
 use-java-7 () {
-    export JAVA_HOME=$JAVA_7
+	export JAVA_HOME=$JAVA_7
 }
 
 use-java-8 () {
-    export JAVA_HOME=$JAVA_8
+	export JAVA_HOME=$JAVA_8
 }
 
 maven-debug () {
-    mvn $@ -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
+	mvn $@ -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
 }
 
 maven-eclipse () {
-    mvn eclipse:configure-workspace -Declipse.workspace="$WORKSPACE" eclipse:clean eclipse:eclipse -Dwtpversion=1.5 $@
+	mvn eclipse:configure-workspace -Declipse.workspace="$WORKSPACE" eclipse:clean eclipse:eclipse -Dwtpversion=1.5 $@
 }
 
 maven-install-eclipse () {
-    mvn clean install $@ && mvn eclipse:configure-workspace -Declipse.workspace="$WORKSPACE" eclipse:clean eclipse:eclipse -Dwtpversion=1.5
+	mvn clean install $@ && mvn eclipse:configure-workspace -Declipse.workspace="$WORKSPACE" eclipse:clean eclipse:eclipse -Dwtpversion=1.5
 }
 
 update-etags () {
-    [ -f TAGS ] && rm TAGS
-    find . -name '*.java' -exec etags -a {} \;
+	[ -f TAGS ] && rm TAGS
+	find . -name '*.java' -exec etags -a {} \;
 }
 
 update-project () {
-    PROJECT_DIR=$1
-    FORMER_DIR=$(pwd)
-    cd "$PROJECT_DIR" || exit
-    PROJECT_NAME=$(basename "$PROJECT_DIR")
-    echo "* ${BOLD}$PROJECT_NAME${NORMAL}"
-    [ -d ".git" ] && git up
-    [ -d ".svn" ] && svn update
-    #   update-etags
-    echo ""
-    cd "$FORMER_DIR" || exit
+	PROJECT_DIR=$1
+	FORMER_DIR=$(pwd)
+	cd "$PROJECT_DIR" || exit
+	PROJECT_NAME=$(basename "$PROJECT_DIR")
+	echo "* ${BOLD}$PROJECT_NAME${NORMAL}"
+	[ -d ".git" ] && git up
+	[ -d ".svn" ] && svn update
+	#   update-etags
+	echo ""
+	cd "$FORMER_DIR" || exit
 }
 
 update-all () {
-    for dir in $(find "$HOME" -type d -iname '.git' -o -maxdepth 3 -iname '.svn' 2> /dev/null | xargs dirname | sort); do
-        update-project "$dir"
-    done
+	for dir in $(find "$HOME" -type d -iname '.git' -o -maxdepth 3 -iname '.svn' 2> /dev/null | xargs dirname | sort); do
+		update-project "$dir"
+	done
 }
 
 build-all () {
-    FORMER_DIR=$(pwd)
-    for dir in $(find "$HOME/projets/" -type f -maxdepth 2 -name 'pom.xml' 2> /dev/null | xargs dirname | sort); do
-        cd "$dir" || exit
-        echo "building $dir..."
-        mvn clean install -U &> "$HOME/projets/mvn-output.log"
-        if [ $? != 0 ]; then
+	FORMER_DIR=$(pwd)
+	for dir in $(find "$HOME/projets/" -type f -maxdepth 2 -name 'pom.xml' 2> /dev/null | xargs dirname | sort); do
+		cd "$dir" || exit
+		echo "building $dir..."
+		mvn clean install -U &> "$HOME/projets/mvn-output.log"
+		if [ $? != 0 ]; then
 
-            echo "build failed!" ; cp "$HOME/projets/mvn-output.log" "$HOME/projets/mvn-output-$(basename $dir).log"
-        fi
-    done
-    rm "$HOME/projets/mvn-output.log"
-    cd "$FORMER_DIR" || exit
+			echo "build failed!" ; cp "$HOME/projets/mvn-output.log" "$HOME/projets/mvn-output-$(basename $dir).log"
+		fi
+	done
+	rm "$HOME/projets/mvn-output.log"
+	cd "$FORMER_DIR" || exit
 }
 
 
