correct bash warnings

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -113,18 +113,18 @@ update-etags () {
 update-project () {
     PROJECT_DIR=$1
     FORMER_DIR=$(pwd)
-    cd "$PROJECT_DIR"
+    cd "$PROJECT_DIR" || exit
     PROJECT_NAME=$(basename "$PROJECT_DIR")
     echo "* ${BOLD}$PROJECT_NAME${NORMAL}"
     [ -d ".git" ] && git up
     [ -d ".svn" ] && svn update
     #   update-etags
     echo ""
-    cd "$FORMER_DIR"
+    cd "$FORMER_DIR" || exit
 }
 
 update-all () {
-    for dir in $(find $HOME -type d -iname '.git' -o -maxdepth 3 -iname '.svn' 2> /dev/null | xargs dirname | sort); do
+    for dir in $(find "$HOME" -type d -iname '.git' -o -maxdepth 3 -iname '.svn' 2> /dev/null | xargs dirname | sort); do
         update-project "$dir"
     done
 }
@@ -132,16 +132,16 @@ update-all () {
 build-all () {
     FORMER_DIR=$(pwd)
     for dir in $(find "$HOME/projets/" -type f -maxdepth 2 -name 'pom.xml' 2> /dev/null | xargs dirname | sort); do
-        cd "$dir"
+        cd "$dir" || exit
         echo "building $dir..."
         mvn clean install -U &> "$HOME/projets/mvn-output.log"
         if [ $? != 0 ]; then
 
-            echo "build failed!" ; cp "$HOME/projets/mvn-output.log" $HOME/projets/mvn-output-$(basename $dir).log
+            echo "build failed!" ; cp "$HOME/projets/mvn-output.log" "$HOME/projets/mvn-output-$(basename $dir).log"
         fi
     done
     rm "$HOME/projets/mvn-output.log"
-    cd "$FORMER_DIR"
+    cd "$FORMER_DIR" || exit
 }
 
 # define a few colours
